name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Configure ntp time
      run: |
        echo Setting ntp time
        sudo ntptime -T 37
